# Test GLMSingleAccess Class

This notebook tests all functions in the GLMSingleAccess class.

In [1]:
import sys
import numpy as np
from pathlib import Path
from pprint import pprint
sys.path.append('..')
from glmsingle_access import GLMSingleAccess

In [2]:
# Initialize the GLMSingleAccess instance
glm_access = GLMSingleAccess()

# Test parameters
test_sub = 1  # test subject
test_ses = 1  # test session
test_video = 1  # test video number

## Test Basic Path Functions

In [3]:
# Test get_glm_dir_path
pprint("GLM Main Directory:")
pprint(glm_access.get_glm_dir_path())

# Test get_nii_dir_path
pprint("\nNii Directory for test subject and session:")
pprint(glm_access.get_nii_dir_path(test_sub, test_ses))

GLM Main Directory:
/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/mainexp_newpreproc

Nii Directory for test subject and session:
/research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/mainexp_newpreproc/sub-001_ses-01_T1W_nordicstc_1.7mm/TYPED_FITHRF_GLMDENOISE_RR


## Test Data Loading Functions

In [4]:
# Test read_shape
print("Data shape:")
shape = glm_access.read_shape(test_sub, test_ses)
print(shape)

Data shape:
Loaded R2 from /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/mainexp_newpreproc/sub-001_ses-01_T1W_nordicstc_1.7mm/TYPED_FITHRF_GLMDENOISE_RR/R2.nii.gz
Shape of R2: (81, 95, 101)
(81, 95, 101)


In [5]:
# Test read_betas
print("Loading betas:")
betas = glm_access.read_betas(test_sub, test_ses)
print(f"Betas shape: {betas.shape}")

Loading betas:
Loaded betas from /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/mainexp_newpreproc/sub-001_ses-01_T1W_nordicstc_1.7mm/TYPED_FITHRF_GLMDENOISE_RR/betasmd.nii.gz
Shape of betas: (81, 95, 101, 720)
Betas shape: (81, 95, 101, 720)


In [6]:
# Test read_affine
print("Loading affine matrix:")
affine = glm_access.read_affine(test_sub)
print(f"Affine matrix:\n{affine}")

Loading affine matrix:
affine matrix source path: /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/anat-3T/sub-001/fiducial/epi_1.7mm/sub-001_ses-3Tanat_T1w_FS_T2BM_crop_resampled.nii.gz
Affine matrix:
[[-1.70000005e+00 -1.82010465e-18  7.91624211e-10  6.90028534e+01]
 [ 7.91624211e-10 -2.47386348e-11  1.70000005e+00 -7.75177841e+01]
 [ 0.00000000e+00 -1.70000005e+00 -2.47386348e-11  9.26971741e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [7]:
# Test read_header
print("Loading header:")
header = glm_access.read_header(test_sub)
print(f"Header info:\n{header}")

Loading header:
affine matrix source path: /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/anat-3T/sub-001/fiducial/epi_1.7mm/sub-001_ses-3Tanat_T1w_FS_T2BM_crop_resampled.nii.gz
Header info:
<class 'nibabel.nifti1.Nifti1Header'> object, endian='<'
sizeof_hdr      : 348
data_type       : b''
db_name         : b''
extents         : 0
session_error   : 0
regular         : b'r'
dim_info        : 0
dim             : [  3  81  95 101   1   1   1   1]
intent_p1       : 0.0
intent_p2       : 0.0
intent_p3       : 0.0
intent_code     : none
datatype        : float32
bitpix          : 32
slice_start     : 0
pixdim          : [-1.   1.7  1.7  1.7  0.   0.   0.   0. ]
vox_offset      : 0.0
scl_slope       : nan
scl_inter       : nan
slice_end       : 0
slice_code      : unknown
xyzt_units      : 2
cal_max         : 0.0
cal_min         : 0.0
slice_duration  : 0.0
toffset         : 0.0
glmax           : 0
glmin           : 0
descrip         : b''
aux_file        : b''
qf

In [8]:
# Test read_meanvol
print("Loading mean volume:")
meanvol = glm_access.read_meanvol(test_sub, test_ses)
print(f"Mean volume shape: {meanvol.shape}")

Loading mean volume:
Loaded meanvol from /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/mainexp_newpreproc/sub-001_ses-01_T1W_nordicstc_1.7mm/TYPED_FITHRF_GLMDENOISE_RR/meanvol.nii.gz
Shape of meanvol: (81, 95, 101)
Mean volume shape: (81, 95, 101)


In [9]:
# Test read_R2
print("Loading R2:")
R2 = glm_access.read_R2(test_sub, test_ses)
print(f"R2 shape: {R2.shape}")

Loading R2:
Loaded R2 from /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/mainexp_newpreproc/sub-001_ses-01_T1W_nordicstc_1.7mm/TYPED_FITHRF_GLMDENOISE_RR/R2.nii.gz
Shape of R2: (81, 95, 101)
R2 shape: (81, 95, 101)


In [10]:
# Test read_R2_mask
print("Creating R2 mask:")
R2_mask = glm_access.read_R2_mask(test_sub, test_ses, threshold=0.2)
print(f"R2 mask shape: {R2_mask.shape}")
print(f"Number of voxels above threshold: {np.sum(R2_mask)}")

Creating R2 mask:
Loaded R2 from /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/mainexp_newpreproc/sub-001_ses-01_T1W_nordicstc_1.7mm/TYPED_FITHRF_GLMDENOISE_RR/R2.nii.gz
Shape of R2: (81, 95, 101)
Shape of R2 mask: (81, 95, 101)
R2 mask shape: (81, 95, 101)
Number of voxels above threshold: 336275


In [11]:
# Test read_video_betas
print("Loading video betas:")
video_betas = glm_access.read_video_betas(test_sub, test_video)
if video_betas is not None:
    print(f"Video betas shape: {video_betas.shape}")
else:
    print("Video betas file not found")

Loading video betas:
File /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/video_betas/sub-001/1.7mm/TYPED_FITHRF_GLMDENOISE_RR/fw/0001_fw_betas.nii does not exist
Video betas file not found


## Test Different Parameters

In [12]:
# Test with different GLM types and resolutions
alternate_glmtype = "TYPED_FITHRF_GLMDENOISE_RR"
alternate_resolution = "1.7mm"

print("Testing with alternate parameters:")
betas = glm_access.read_betas(test_sub, test_ses, 
                             glmtype=alternate_glmtype,
                             resolution=alternate_resolution)
print(f"Betas shape with alternate parameters: {betas.shape}")

Testing with alternate parameters:
Loaded betas from /research/FGB-CognitivePsychology-Knapen/shared/2024/visual/AOT/derivatives/glmsingle/mainexp_newpreproc/sub-001_ses-01_T1W_nordicstc_1.7mm/TYPED_FITHRF_GLMDENOISE_RR/betasmd.nii.gz
Shape of betas: (81, 95, 101, 720)
Betas shape with alternate parameters: (81, 95, 101, 720)
